site_name: Bitcoin Pro 
site_author: FunCoder
site_description: >-
  In Bitcoin, we trust.
repo_name: bitcoin-pro
repo_url: https://github.com/wangzhe3224/bitcoin-pro

copyright: Copyright &copy; 2022-present <a href="https://github.com/wangzhe3224" target="_blank" rel="noopener noreferrer">FunCoder</a> | Support me with some Sats ₿ - bc1qsexhgghqwsqzsdatdwp0js3j68wxff36vqc7r72ucmc0wq69w3ns62hwaw

theme:
  name: material
  favicon: assets/bitcoin.png
  logo: assets/bitcoin.png
  language: zh
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  palette:
    - primary: dark
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  custom_dir: overrides

plugins:
  - search:
       lang: en
       indexing: 'full'
       prebuild_index: true
  - tags
  # doc : https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/
  - git-revision-date-localized:
      custom_format: "%d. %B %Y"
      timezone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
  
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html 
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-8RFRYS5M9T
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wangzhe3224 
  generator: false

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 前言: "index.md"
  - 比特币随想:
    - "tb/think_bitcoin.md"
    - "tb/thinking_bitcoin_2.md"
    - "tb/thinking_bitcoin_3.md"
    - "tb/think_bitcoin_3.md"
    - "tb/thinking_bitcoin_4.md"
    - "tb/thinking_bitcoin_5.md"
    - "tb/thinking_bitcoin_6.md"
    - "tb/thinking_bitcoin_7.md"
    - "tb/thinking_bitcoin_8.md"
    - "tb/thinking_bitcoin_9.md"
    - "tb/think_bitcoin_9.md"
    - "tb/thinking_bitcoin_12.md"
    - "tb/thinking_bitcoin_13.md"
    - "tb/thinking_bitcoin_14.md"
    - "tb/thinking_bitcoin_15.md"
    - "tb/thinking_bitcoin_16.md"
    - "tb/thinking_bitcoin_17.md"
    - "tb/thinking_bitcoin_18.md"
    - "tb/thinking_bitcoin_19.md"
    - "tb/thinking_bitcoin_20.md"
    - "tb/thinking_bitcoin_21.md"
  - 21 Ways:
    - "21_ways/toc.md"
    - "21_ways/index.md"
    - "21_ways/ch00.md"
    - "21_ways/ch001.md"
    - "21_ways/ch01.md"
    - "21_ways/ch02.md"
    - "21_ways/ch03.md"
    - "21_ways/ch06.md"
  - 其他:
    - "others/nostr.md"
    - "others/bitcoin_wallet.md"
    - "others/electrum_wallet.md"
  - 资源: "resources.md"
  - 机构: "organizations.md"